### ISSUE TITLE
NoSuchFieldError - field_70118_ct at furgl.babyMobs.common.entity.monster.EntityBabyIronGolem.func_70636_d

### ISSUE THREAD

**Issue by Vaxidd** [Furgl/BabyMobs#5] opened 2016-12-28 19:02 UTC
Please see attached crash report.

[crash-2016-12-28_15.45.49-server.txt](https://github.com/Furgl/BabyMobs/files/676116/crash-2016-12-28_15.45.49-server.txt)

**Comment by Furgl** [comment] 2017-01-16 23:01
1.7.10 is no longer supported, unfortunately. This issue should be fixed in 1.10.2+, I suggest you update.

**Closed as completed by Furgl** 2017-01-16 23:01 UTC
Labels: wontfix

**Comment by Vaxidd** [comment] 2017-01-17 00:00
Even so, it is a fairly known bug. Most of the mods I play with don't
support 1.10, they're "stuck" at 1.7.10. Couldn't you please find the time
to fix this issue, since, as you said, it has been fixed in newer versions,
please?

**Comment by Furgl** [comment] 2017-01-17 00:29
It is a common bug, typically caused by a misunderstanding of how Minecraft decompiles and recompiles. Baby Mobs was my first mod, so I made a few errors that would cause this bug to occur in the first few releases. 
I no longer have a 1.7.10 development workspace set up for Baby Mobs so, even though this would be an easy fix, it would take quite a while to set up my workspace to do it. 
1.7.10 has been outdated for about two and a half years now, so if you're still using mods that haven't updated past 1.7.10, it's probably time to move on from them.
