### ISSUE TITLE
[1.11.2] Crash with Harder Farming mod

### ISSUE THREAD

**Issue by Insane96** [Furgl/BabyMobs#15] opened 2017-09-10 07:48 UTC
I've reported this to HarderFarming too
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 9/10/17 9:44 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:95)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at net.minecraft.entity.passive.EntityChicken.func_70636_d(SourceFile:82)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at furgl.babyMobs.common.entity.monster.EntityZombieChicken.func_70071_h_(EntityZombieChicken.java:180)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:95)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at net.minecraft.entity.passive.EntityChicken.func_70636_d(SourceFile:82)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at furgl.babyMobs.common.entity.monster.EntityZombieChicken.func_70071_h_(EntityZombieChicken.java:180)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: babymobs:zombiechicken (furgl.babyMobs.common.entity.monster.EntityZombieChicken)
	Entity ID: 6669
	Entity Name: Zombie Chicken
	Entity's Exact location: 15.50, 37.00, -73.50
	Entity's Block location: World: (15,37,-74), Chunk: (at 15,2,6 in 0,-5; contains blocks 0,0,-80 to 15,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: [EntityBabyZombie['Baby Zombie'/6668, l='Harder Baby Mobs', x=15.50, y=37.45, z=-73.60]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Harder Baby Mobs
	All players: 1 total; [EntityPlayerMP['Insane96MCP'/1733, l='Harder Baby Mobs', x=70.34, y=71.00, z=-42.57]]
	Chunk stats: ServerChunkCache: 732 Drop: 0
	Level seed: 5254136290266529137
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (24,64,-44), Chunk: (at 8,4,4 in 1,-3; contains blocks 16,0,-48 to 31,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1851 game time, 1851 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 34717 (now: false), thunder time: 28124 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 156115192 bytes (148 MB) / 547520512 bytes (522 MB) up to 3157786624 bytes (3011 MB)
	JVM Flags: 18 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3078m -Xms256m -XX:PermSize=256m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.1.2429 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2429.jar) 
	UCHIJAAAA	forge{13.20.1.2429} [Minecraft Forge] (forge-1.11.2-13.20.1.2429.jar) 
	UCHIJAAAA	hardlib{3} [HardLib] (1.11.2-HardLib-v3.jar) 
	UCHIJAAAA	harderfarming{3.0.1a} [Harder Farming] (1.11.2-Harderfarming-3.0.1a.jar) 
	UCHIJAAAA	babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.11.2-1.5.4.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Insane96MCP'/1733, l='Harder Baby Mobs', x=70.34, y=71.00, z=-42.57]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Furgl** [comment] 2017-09-10 15:08
Are you able to reproduce this crash, does it happen consistently, and does it only happen under certain conditions?

**Comment by Insane96** [comment] 2017-09-11 07:39
Yes. Create a new world, set difficulty to peaceful asap. Then `/gamerule doMobSpawning false`.
Set difficulty back to not-peaceful and spawn a baby zombie (with zombiefied chicken). After a while (I think when he tries to move) game crashes

**Comment by Furgl** [comment] 2017-09-11 22:52
It looks like Draco18s has a fix for this issue. If that's not the case, let me know and I'll reopen this and take a look at it again.

**Closed as completed by Furgl** 2017-09-11 22:52 UTC
